my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from posts.views import UserPosts

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', views.ListCategory2.as_view(), name='index_page'),

    url(r'^categories/', include("categories.urls",namespace="categories")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^posts/", include("posts.urls", namespace="posts")),

    url(r"^test/$", views.TestPage.as_view(), name='test'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name='thanks'),
    url(r"by/(?P<username>[-\w]+)/$", UserPosts.as_view(),name="for_user"),
    # url(r"^profile/$", views.ProfileView.as_view(), name='profile'),

    path('national_news/', views.national_news, name='national'),
    path('sports/',views.sports_news, name='sports'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

my_site/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.post_detail,name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),

    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),

]

my_site/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from categories.models import Category
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, related_name="user_of_post_model", on_delete=models.CASCADE)
    created_at =  models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    category = models.ForeignKey(Category, related_name="posts",on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={"username":self.user.username, "pk":self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ('user', 'message')


class Comment(models.Model):
    post = models.ForeignKey('posts.Post',on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approve_comment = models.BooleanField(default=False)

    def approve(self):
        self.approve_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("all")

    def __str__(self):
        return self.text

my_site/posts/forms.py
from django import forms
from . models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        fields = ("title","message", "category")
        model  = Post

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'message':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

my_site/posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import(TemplateView,ListView,
                                DetailView, CreateView,
                                UpdateView, DeleteView,
                                RedirectView,
                                )
from braces.views import SelectRelatedMixin

from . forms import PostForm, CommentForm
from . models import Post, Comment
from categories import models

from sorl.thumbnail import  get_thumbnail
from resizeimage import resizeimage
from accounts.models import UserProfileInfo
from my_site import settings
from django.contrib.auth.models import User
# Create your views here.

class CreatePost(LoginRequiredMixin, CreateView):
    redirect_field_name = 'posts/post_detail.html'
    form_class = PostForm
    model = Post
    import misaka

    def form_valid(self, form):
        self.object = form.save(commit=False)
        try:
            all_members = models.CategoryMember.objects.filter(
                user=self.request.user,
                category__slug=self.object.category.slug).get()
        except models.CategoryMember.DoesNotExist:
            self.warning="Join the category first!"
            return redirect("categories:single",self.object.category.slug)
        else:
            print('1 username %s post_pk %s' % (self.request.user.username, self.object.pk))
            self.object.user=self.request.user
            print('2 username %s post_pk %s' % (self.request.user.username, self.object.pk))
            self.object.save()
            print('3 username %s post_pk %s' % (self.request.user.username, self.object.pk))
            return super().form_valid(form)


def post_detail(request, username, pk):
    post = get_object_or_404(Post, pk=pk)
    new_comment = False
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # Create Comment object but don't save to database yet
            comment = form.save(commit=False)
            # Assign the current post to the comment
            comment.post = post
            # Save the comment to the database
            comment.save()
            new_comment = True

            if new_comment == True:
                form = CommentForm()
            return render(request, 'posts/post_detail.html', {'post':post,
                                                        'new_comment':new_comment,
                                                             'comment_form':form})
    if request.method != 'POST':
        form = CommentForm()
        new_comment = False
        # request.session['new_comment'] = "False"
    return render(request, 'posts/post_detail.html', {'post':post,
                                                'new_comment':new_comment,
                                                     'comment_form':form})


class PostList(ListView, SelectRelatedMixin):
    model = Post
    select_related = ("user", "category")



from django.contrib.auth.models import User
from categories.models import CategoryMember, Category
class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("user_of_post_model").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.user_of_post_model.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        current_user = UserProfileInfo.objects.filter(
            user__id__iexact = self.post_user.id
        ).get()

        post_of_user = self.post_user.user_of_post_model.all()
        single_post = []

        for post in post_of_user:
            single_post.clear()
            single_post.append(str(post))

        single_post = post_of_user[0]
        print('first 2 posts\n',str(single_post)[3:10])

        user_categories= []
        category_list = []
        single_list = []

        for member in CategoryMember.objects.all():
            if member.user == self.post_user:
                category_list.clear()
                category_list.append(member.category.name)
                category_list.append(member.category.slug)

                user_categories.append(category_list[:])
            else:
                print('not found')

        print('user categories\n',user_categories)

        if current_user.profile_pic:
            profile_pic = True
            picture = current_user.profile_pic
            edited_picture = get_thumbnail(picture, '350x350', quality=99, format='PNG')
        else:
            profile_pic = False
            root = settings.MEDIA_ROOT
            import os
            root1 = os.path.join(root, 'profile_pics/no-image.png')
            picture = root1
            edited_picture = get_thumbnail(picture, '350x350', quality=99, format='PNG')
            # resizeimage.resize_cover(picture, [200, 100], validate=False)
            # rescale_image(picture,width=100,height=100)

        user_info = {
            'current_user':current_user,
            'user_categories':user_categories,
            'edited_picture':edited_picture,
            'profile_pic':profile_pic,
            'post_user':self.post_user,
        }
        user_info_list = [
            current_user, user_categories, edited_picture,
            profile_pic, self.post_user, self.post_user.username,
            self.post_user.first_name, self.post_user.last_name,
            self.post_user.email, self.post_user,
        ]
        # print(user_info)
        context['user_info_list'] = user_info_list
        return context

# class PostDetail(SelectRelatedMixin, DetailView):
#     model = Post
#     select_related = ("user", "category")
#
#     def get_queryset(self):
#         query_set = super().get_queryset()
#         return query_set.filter(
#             user__username__iexact=self.kwargs.get("username")
#         )


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ("user", "category")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        user_id = self.request.user.id
        return queryset.filter(user_id=user_id)

    def delete(self,*args,**kwargs):
        messages.success(self.request, "Post is deleted!")
        return super().delete(*args,**kwargs)


# def add_comment_to_post(request,username, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.save()
#             return redirect('posts:single', username=post.user.username, pk=post.pk)
#     else:
#         form = CommentForm()
#     return render(request, 'posts/post_detail.html', {'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('posts:single', username=comment.post.user.username, pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    post = comment.post
    comment.delete()
    return redirect('posts:single',username=post.user.username, pk=post.pk)

my_site/posts/templates/posts/_post.html
  <div class="techfont">
    <div class="row">
      <div class="col-md-1">

      </div>
      <div class="col-md-10">
        <h3><br><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"><strong>{{post.title}} </strong> </a></h2>
        <h6><a href="{% url 'posts:for_user' username=post.user.username %}">{{post.user.username}}</a>
        <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>{{post.created_at}} </time>
        {% if post.category %}
          <span>in <a href="{% url 'categories:single' slug=post.category.slug %}">{{post.category.name}}</a> </span>
        {% endif %}
        <br>

          <br>
          <h3 class="message_html">{{post.message_html|safe}}</h3>

          {% if user.is_authenticated and user == post.user and not hide_delete%}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
    					<span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span>
    				</a>
          {% endif %}

      </div>
    </div>
    </div>

my_site/posts/templates/posts/comment_form.html
{% extends "posts/post_base.html" %}

{% block prepost %}
  <div class="jumbotron">
    <h2>New Comment</h2>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="save btn btn-default">Submit</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

  </div>

{% endblock %}

my_site/posts/templates/posts/post_base.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static "assets/css/style2.css" %}">

{% block content %}
<section id="posts" class="steps section-bg">
      {% block prepost %}

      {% endblock %}

      {% block post_content %}

      {% endblock %}

      {% block post_post %}

      {% endblock %}

</section>

{% endblock %}

my_site/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<div class="row">
	<div class="col-md-2">	</div>

	<div class="col-md-8">
		<h3><br>Are you sure you want to delete "<span style="font-size:32px; color:red;">{{post.title}}</span>"?</h3>
	</div>

	<div class="col-md-2">	</div>
</div>

<div class="posts">
	<div class="row">
		<div class="col-md-1">	</div>
		<div class="col-md-10">
			{% include "posts/_post.html" with post=object hide_delete=True %}
		</div>
		<div class="col-md-1">	</div>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-2">	</div>
	<div class="col-md-8">
		<form method="POST">
			{% csrf_token %}
			<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
			<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-default">
				<span style="font-weight:bold">Cancel</span>
			</a>
		</form>
	</div>

	<div class="col-md-2">	</div>
</div>


{% endblock %}

my_site/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% load static %}

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  {% block post_content %}
  <hr>
  <div class="row">
    <div class="col-md-1"> </div>
    <div class="col-md-10">
      <div class="container">
        {% include "posts/_post.html" %}
        <br><br><br>

        {# add_comment_to_post section #}
          <div class="row">
            <div class="col-md-1">  </div>
            <div class="col-md-10"> <hr> </div>
            <div class="col-md-1">  </div>
            <div class="col-md-1">  </div>

            <div class="col-md-8">
              <h6><strong>Comment on this post</strong> </h6>
              <form class="" action="" method="post">
                {% csrf_token %}
                {{comment_form.as_p}}
            </div>

            <div class="col-md-3">
                <button type="submit" class="save btn btn-primary">Add Comment</button>
              </div>
              <div class="col-md-1">  </div>
              <div class="col-md-10"> <hr> </div>
              </form>
            <script>var editor = new MediumEditor('.editable');</script>
          </div>
        <br>
      </div>
    </div>
    </div>

      {# comment section #}
      <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8 single-comment">

          {% if new_comment %}
              <div class="new_comment">
                  <h6 class="">***Thanks for your response to this post. New Comment has been added.
                    The right to approve or delete comments is given to the author.
                    <br>Comment will be shown in the comment section when approved!
                  </h6>
              </div>
                {% endif %}

                <hr><h3>Comments by other authors</h3><hr>
                <div class="comment">
                  {% for comment in post.comments.all %}

                    {% if  comment.approve_comment  %}

                    <div class="single">
                      <hr>
                              <h4 class="message_text">{{comment.text|safe}}</h4>
                              <div class="container row">

                                <p>{{comment.created_date}}</p>

                                <div class="col-md-1"> </div>
                                <p>Posted by: <strong>{{ comment.author }}</strong></p>
                            </div>
                          <hr>
                    </div>
                   {% endif %}

                    {% if post.user.username == user.username and not comment.approve_comment %}
                      <div class="single">
                        <hr>
                          <h4 class="message_text">{{comment.text|safe|linebreaks}}</h4>
                          <div class="container row">

                            <div class="col-md-4">
                              <p>{{comment.created_date}}</p>
                            </div>
                            <div class="col-md-8">
                            <p>Posted by: <strong>{{ comment.author }}</strong></p>
                            </div>
                            <a class="btn btn-danger" href="{% url 'posts:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove">Delete</span></a>
                            <div class="col-md-1"> </div>
                            <a class="btn btn-primary" href="{% url 'posts:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok">Approve</span></a>

                          </div>

                        <hr>
                      </div>

                    {% endif %}

                    {% empty %}
                      <p>No Comments posted by anyone</p>
                    {% endfor %}
        </div>
      </div>


{% endblock %}

my_site/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}

{% block post_content %}
<section id="news" class="steps section-bg">
  <div class="jumbotron container">
    <h4><br><strong>Write a new Post</strong> <br> </h4>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {# {% bootstrap_form form %} #}

      <input type="submit" class="btn btn-primary" value="Post">
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

  </div>

</section>

{% endblock %}

my_site/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

  {% block post_content %}
    <div class="row">
      <div class="col-md-1">

      </div>
      <div class="col-md-10">
        {% for post in post_list %}
          {% include "posts/_post.html" %}
        {% endfor %}
      </div>
    </div>
  {% endblock %}

my_site/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% load thumbnail %}
{% load static %}
{% load custom_tag %}

{% block content %}
  <section id="steps" class="steps section-bg">

    <div class="content-item">
      <div class="row">
        <div class="col-lg-5 col-md-5">

          {% if user_info_list.3 %}
            <img src="{{user_info_list.2.url}}" alt="">
          {% else %}

          <img src="{{user_info_list.2.url}}" alt="">
          {% endif %}
        </div>

        <div class="col-lg-2 col-md-2">
            <br><br><br><br> <hr>
            <h3 class="user-title">Username </h3>

            <h4 class="info2">First Name </h4>
            <h4 class="info2">Last Name </h4>
            <h4 class="info2">Email </h4>
        <hr>
        </div>

        <div class="col-md-5 col-lg-5">
          <br><br><br><br> <hr>
          <h3 class="user"> {{user_info_list.5}}</h3>

          {% if user_info_list.6 %}
            <h4 class="info2">{{user_info_list.6}}</h4>
          {% else %}
            <h4 class="info2">NULL</h3>
          {% endif %}

          {% if user_info_list.7 %}
            <h4 class="info2">{{user_info_list.7}}</h3>
          {% else %}
            <h4 class="info2"> NULL</h3>
          {% endif %}

          {% if user_info_list.8 %}
            <h4 class="info2">{{user_info_list.8}}</h3>
          {% else %}
            <h4 class="info2">NULL</h3>
          {% endif %}
        <hr>
        </div>
      </div>
    </div>


    {# ######################## #}
    <div class="container">
      {% block prepost %}
        <div class="row">
          <div class="col-md-6 col-lg-6">
             <ul>
               <li><h3>Categories Joined by <a href="{% url 'posts:for_user' username=user_info_list.5 %}">{{user_info_list.0}}</a></h3></li>

                {% for categories in user_info_list.1 %}
                    <ul>
                      <li><a href="{% url 'categories:single' slug=categories.1 %}"> {{categories.0}}</a> </li>
                    </ul>
                {% endfor %}
                <br>
              <li><h5 class="techfont">Post written by {{user_info_list.5}} : {{post_list.count}} </h5></li>
             </ul>
          </div>
        </div>
      {% endblock %}

      {% block post_content %}
      <div class="row">
        <div class="col-md-1">  </div>

        <div class="col-md-10 col-lg-10">
          <br>
            {% for post in post_list %}
              <hr>
              <div class="row">
                <div class="col-md-1">

                </div>
                <div class="col-md-10">
                  <h3><br><a style="color:#0d3569; font-size:30px;" href="{% url 'posts:single' username=post.user.username pk=post.pk %}"><strong>{{post.title}} </strong> </a></h2>
                  <h6><a href="{% url 'posts:for_user' username=post.user.username %}">{{post.user.username}}</a>
                  <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a>{{post.created_at}} </time>
                  {% if post.category %}
                    <span>in <a href="{% url 'categories:single' slug=post.category.slug %}">{{post.category.name}}</a> </span>
                  {% endif %}
                  <br>

                    <br>
                    <h3 class="message_html">{{post.message_html|safe|truncatechars:300}}

                        <span><a style="font-size:17px;" href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.message_html|check_char}}</a> </span>
                      {# {% endif %} #}
                    </h3>

                    {% if user.is_authenticated and user == post.user and not hide_delete%}
                      <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger">
              					<span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span>
              				</a>
                    {% endif %}
                </div>
              </div>
              <hr>
            {% endfor %}
        </div>
      </div>

      {% endblock %}
    </div>
  </section>

{% endblock %}