my_site/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    url(r'register/$',views.register, name='register'),
    url(r'user_login/$', views.user_login, name='login'),
    url(r'logout/$', views.user_logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from posts.views import UserPosts

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', views.ListCategory2.as_view(), name='index_page'),

    url(r'^categories/', include("categories.urls",namespace="categories")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^posts/", include("posts.urls", namespace="posts")),

    url(r"^test/$", views.TestPage.as_view(), name='test'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name='thanks'),
    url(r"by/(?P<username>[-\w]+)/$", UserPosts.as_view(),name="for_user"),
    # url(r"^profile/$", views.ProfileView.as_view(), name='profile'),

    path('national_news/', views.national_news, name='national'),
    path('sports/',views.sports_news, name='sports'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

my_site/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.post_detail,name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),

    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),

]

my_site/templates/about.html
{% extends "base.html" %}

{% block content %}






{% endblock %}

my_site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Thoughts</title>
  <meta content="" name="keywords">

  <!-- Favicons -->

  <link href="{% static '/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static '/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/style2.css' %}" rel="stylesheet">


  <!-- {# MEDIUM STYLE EDITOR#} -->
      <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

</head>

<body>
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'index_page' %}">Thoughts</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% url 'index_page' %}"><img src="{% static 'assets/img/logo.png' %}" alt="" class="img-fluid"></a> -->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li><a href="#"></a></li>
          <li><a href="{% url 'national' %}">Today's News</a></li>
          <li><a href="{% url 'categories:all' %}">Categories</a></li>
          <li class="drop-down"><a href="#projects">Projects</a>
            <ul>
              <li><a href="#">URL Classification</a></li>
              <li><a href="#">News Aggregator</a></li>
              <li><a href="#">Crawling Top 100 Movies[IMDB]</a></li>
              <li><a href="#">Crawling Top 100 Movies[RottenTomatoes]</a></li>
            </ul>
          </li>

          <li class="drop-down"><a href="">CSE Blogs</a>
            <ul>
              <li><a href="/categories/posts/in/django">Django</a></li>
              <li class="drop-down"><a href="#">Machine Learning</a>
                <ul>
                  <li><a href="/categories/posts/in/regression">Regression</a></li>
                  <li><a href="/categories/posts/in/classification">Classification</a></li>
                  <li><a href="/categories/posts/in/clustering">Clastering</a></li>
                  <li><a href="/categories/posts/in/nlp">NLP</a></li>
                </ul>
              </li>
              <li class="drop-down"><a href="#">Deep Learning</a>
                <ul>
                  <li><a href="#">ANN</a></li>
                  <li><a href="#">CNN</a></li>
                </ul>
              </li>
              <li class="drop-down"><a href="">Crawling</a>
                <ul>
                  <li><a href="#">Beautiful Soap</a></li>
                  <li><a href="#">Scrapy</a></li>
                  <li><a href="#">Selenium</a></li>
                  <li><a href="#">Scraping and Django Model Integration</a> </li>
                </ul>
              </li>
            </ul>
          </li>
          <li class="posts"><a href="{% url 'posts:create' %}">Post</a></li>
          <li><a href="/#about">About</a></li>
          <li><a href="/#contact">Contact</a></li>

          {% if user.is_authenticated %}
          <li class="drop-down"><a class="user" href="#">{{user.username}}</a>
              <ul class="user-link">
                {% if not user.is_superuser %}
                  <li ><a class="profile" href="{% url 'posts:for_user' username=user.username %}">Profile</a></li>
                  <li ><a class="logout" href="{% url 'accounts:logout' %}">Log out</a></li>
                {% else %}
                  <li ><a class="logout" href="{% url 'accounts:logout' %}">Log out</a></li>
                {% endif %}
              </ul>
            </li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
          {% endif %}

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header>
  <!-- End Header -->

    <div class="full-body">
      {% block content %}

      {% endblock %}
    </div>


    <!-- ======= Footer ======= -->
    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">

            <div class="col-lg-6 col-md-6">
              <div class="footer-info">
                <h3>Sayad Ahmed Chowdhury (Shaurov)</h3>
                <p>
                  Halishahar <br>
                  B-block, Chittagong<br><br>
                  <strong>Phone:</strong> +8801752296069<br>
                  <strong>Email:</strong> sacshaurov05@gmail.com<br>
                </p>
                <div class="social-links mt-3">
                  <a href="https://www.facebook.com/sayad.ahmed.3720/" class="facebook"><i class="bx bxl-facebook"></i></a>
                  <a href="https://www.instagram.com/ahmed_shaurov.10/?hl=en" class="instagram"><i class="bx bxl-instagram"></i></a>
                  <!-- <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a> -->
                  <a href="https://www.linkedin.com/in/sayad-ahmed-b88a60195/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
              </div>
            </div>

            <div class="col-lg-6 col-md-6 footer-links">
              <h4>Go To</h4>
              <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="{% url 'index_page' %}">Home</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="/#about">About Me</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="{% url 'categories:all' %}">Categories</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="/#projects">Projects</a></li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </footer>


  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js'%}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>


  </body>

  </html>

my_site/templates/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Thoughts</title>
  <meta content="" name="keywords">

  <!-- Favicons -->

  <link href="{% static '/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static '/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">



  <!-- {# MEDIUM STYLE EDITOR#} -->
      <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

</head>

<body>
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'index_page' %}">Thoughts</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="{% url 'index_page' %}"><img src="{% static 'assets/img/logo.png' %}" alt="" class="img-fluid"></a> -->
      </div>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li><a href="#"></a></li>
          <li><a href="{% url 'national' %}">Today's News</a></li>
          <li class="drop-down"><a href="#">Projects</a>
            <ul>
              <li><a href="#">URL Classification</a></li>
              <li><a href="#">News Aggregator</a></li>
              <li><a href="#">Crawling Top 100 Movies[IMDB]</a></li>
              <li><a href="#">Crawling Top 100 Movies[RottenTomatoes]</a></li>
            </ul>
          </li>

          <!-- <li><a href="#portfolio">Projects</a></li> -->
          <li class="drop-down"><a href="">CSE Blogs</a>
            <ul>
              <li><a href="#">Django</a></li>
              <li class="drop-down"><a href="#">Machine Learning</a>
                <ul>
                  <li><a href="#">Regression</a></li>
                  <li><a href="#">Classification</a></li>
                  <li><a href="#">Clastering</a></li>
                  <li><a href="#">NLP</a></li>
                </ul>
              </li>
              <li class="drop-down"><a href="#">Deep Learning</a>
                <ul>
                  <li><a href="#">ANN</a></li>
                  <li><a href="#">CNN</a></li>
                </ul>
              </li>
              <li class="drop-down"><a href="#">Crawler</a>
                <ul>
                  <li><a href="#">Beautiful Soap</a></li>
                  <li><a href="#">Scrapy</a></li>
                  <li><a href="#">Selenium</a></li>
                  <li><a href="#">Scraping and Django Model Integration</a> </li>
                </ul>
              </li>
            </ul>
          </li>
          <li class="posts"><a href="{% url 'posts:create' %}">Post</a></li>
          <li><a href="{% url 'categories:all' %}">Category</a></li>
          <li><a href="#about">Myself</a></li>
          <li><a href="#contact">Contact</a></li>

          {% if user.is_authenticated %}
          <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Log in</a></li>
          {% endif %}

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <!-- <section id="steps" class="section-bg"> -->
      {% block content %}

      {% endblock %}
  <!-- </section> -->


    <!-- ======= Footer ======= -->
    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">

            <div class="col-lg-6 col-md-6">
              <div class="footer-info">
                <h3>Sayad Ahmed Chowdhury (Shaurov)</h3>
                <p>
                  Halishahar <br>
                  B-block, Chittagong<br><br>
                  <strong>Phone:</strong> +8801752296069<br>
                  <strong>Email:</strong> sacshaurov05@gmail.com<br>
                </p>
                <div class="social-links mt-3">
                  <a href="https://www.facebook.com/sayad.ahmed.3720/" class="facebook"><i class="bx bxl-facebook"></i></a>
                  <a href="https://www.instagram.com/ahmed_shaurov.10/?hl=en" class="instagram"><i class="bx bxl-instagram"></i></a>
                  <!-- <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a> -->
                  <a href="https://www.linkedin.com/in/sayad-ahmed-b88a60195/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
              </div>
            </div>

            <div class="col-lg-6 col-md-6 footer-links">
              <h4>Go To</h4>
              <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="{% url 'index_page' %}">Home</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">About Me</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Blogs</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Projects</a></li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </footer>


  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js'%}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>


  </body>

  </html>

my_site/templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
  <div class="container text-center text-md-left" data-aos="fade-up">
    <p><br><br><br><br> </p>
    <h1>Welcome to the Blog</h1>
    <h2>Express your thoughts! Share what's on your mind.<br>
      Create your own category and Post your blog! Let your
      thoughts be expressed though your writing.<br><br>
    You can also find many useful categories and blogs written on CSE related topics</h2>
    <a href="#categories" class="btn-get-started scrollto">Get Started</a>
  </div>
</section><!-- End Hero -->

<main id="main">

  <!-- ======= Steps Section ======= -->
  <section id="categories" class="categories section-bg">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-lg-12 col-md-12 content-item">
          <div class="categories">
            <div class="category_link">
              <h2><strong>Categories</strong> </h2>
            </div>
          </div>
        </div>
        {% for category in object_list %}
        <div class="col-lg-4 col-md-6 content-item" data-aos="fade-in" data-aos-delay="500">
          <span>0{{category.pk}}</span>
              <a href="{% url 'categories:single' slug=category.slug %}">
                <h4 class="link_name">{{category.name}}</h4>
              </a>
              <p>{{category.description|safe}}</p>
        </div>
        {% endfor %}

      </div>

    </div>
  </section><!-- End Steps Section -->

  <!-- ======= Features Section ======= -->
  <section id="projects" class="features">
    <div class="container">

      <div class="row">
        <div class="col-lg-4 mb-5 mb-lg-0" data-aos="fade-right">
          <ul class="nav nav-tabs flex-column">
            <li class="nav-item">
              <a class="nav-link active show" data-toggle="tab" href="#tab-1">
                <h4>URL Classification</h4>
                <p>Classification of URL using MNB and SGD.</p>
              </a>
            </li>
            <li class="nav-item mt-2">
              <a class="nav-link" data-toggle="tab" href="#tab-2">
                <h4>News Crawler</h4>
                <p>Crawling news from websites and cleaning using BeautifulSoap</p>
              </a>
            </li>
            <li class="nav-item mt-2">
              <a class="nav-link" data-toggle="tab" href="#tab-3">
                <h4>Crawl Top 100 Movies</h4>
                <p>Crawl top 100 movies from IMDB and save in your database.</p>
              </a>
            </li>
            <li class="nav-item mt-2">
              <a class="nav-link" data-toggle="tab" href="#tab-4">
                <h4>Blog Site</h4>
                <p>You can create category and join to write blogs.</p>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-lg-7 ml-auto" data-aos="fade-left">
          <div class="tab-content">
            <div class="tab-pane active show" id="tab-1">
              <figure>
                <img src="{% static "assets/projects5.png" %}" alt="" class="img-fluid">
              </figure>
            </div>

          </div>
        </div>
      </div>

    </div>
  </section><!-- End Features Section -->


  <!-- ======= Testimonials Section ======= -->
  <section id="news" class="testimonials">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h2>Quotes of Computer Scientists and Businessman</h2>
        <p>"I choose a lazy person to do a hard job. Because a lazy person will find an easy way to do it. ~Bill Gates"</p>
      </div>

      <div class="owl-carousel testimonials-carousel" data-aos="fade-up">

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            Coding is today's language of creativity. All our children deserve a chance to become creators instead consumers of computer science.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
            <br><br>
            </p>
          <img src="{% static 'assets/quote1.jfif' %}" class="testimonial-img" alt="">
          <h3>Maria Klawe</h3>
          <h4>Computer Scientist</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
            "The characteristic of great innovators and great companies is they see a space that others do not. They don't just listen to what people tell them; they actually invent something new, something that you didn't know you needed, but the moment you see it, you say, 'I must have it.'"
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'assets/quotes2.jfif' %}" class="testimonial-img" alt="">
          <h3>Erik Schmidt</h3>
          <h4>Businessman and software engineer.</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              "If debugging is the process of removing software bugs, then programming must be the process of putting them in."
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'assets/quote3.jfif' %}" class="testimonial-img" alt="">
          <h3>Edsger Dijkstra</h3>
          <h4>Dutch computer scientist</h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              I have not failed. I've just found 10,000 ways that won't work.
           <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'assets/quote4.jfif' %}" class="testimonial-img" alt="">
          <h3>Thomas A. Edison </h3>
          <h4>American inventor and businessman </h4>
        </div>

        <div class="testimonial-item">
          <p>
            <i class="bx bxs-quote-alt-left quote-icon-left"></i>
              It doesn't make sense to hire smart people
              and then tell them what to do; we hire smart people
              so they can tell us what to do.
            <i class="bx bxs-quote-alt-right quote-icon-right"></i>
          </p>
          <img src="{% static 'assets/quote5.jfif' %}" class="testimonial-img" alt="">
          <h3>Steve Jobs</h3>
          <h4>American business magnate</h4>
        </div>

      </div>

    </div>
  </section><!-- End Testimonials Section -->

  <!-- ======= About Section ======= -->
  <section id="about" class="about">
    <div class="container">

      <div class="row">
        <div class="col-xl-6 col-lg-7" data-aos="fade-right">
          <img src="{% static 'assets/picture2.jpg'%}" class="img-fluid" alt="">
        </div>
        <div class="col-xl-6 col-lg-5 pt-5 pt-lg-0">
          <h3 data-aos="fade-up">Sayad Ahmed Chowdhury</h3>
          <p data-aos="fade-up">
            I have completed BSc (Engineering) in CSE from Noakhali Science
            & Technology University. Now, I have started to write blogs on
            different topics i.e. Machine Learning, Django, Crawler etc.
            <br>Find my posts here <a href="{% url 'posts:for_user' username='shaurov803' %}">shaurov803</a>
          </p>
          <div class="icon-box" data-aos="fade-up">
            <i class="bx bx-cube-alt"></i>
            <a class="title" href="#">Authentication in Django</a>
            <p> Learn how to authenticate an user in a website </p>
          </div>

          <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
            <i class="bx bx-cube-alt"></i>
            <a class="title" href="#">Models in Django</h4></a>
            <p>Model creation and registration of model using Django.</p>
          </div>

          <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
            <i class="bx bx-cube-alt"></i>
            <a class="title" href="#">Crawler</h4></a>
            <p>Learn how to crawl Prothon Alo and Kaler Kontho news websites using BeautifulSoap</p>
          </div>

        </div>
      </div>

    </div>
  </section><!-- End About Section -->

  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h2>Contact</h2>
        <p>Contact with me if needed. Though I am not an expert, but i can help you if it's under my area of knowledge.</p>
        <p>Or else, You can reach me through Email.</p>
      </div>

      <div class="row no-gutters justify-content-center" data-aos="fade-up">

        <div class="col-lg-5 d-flex align-items-stretch">
          <div class="info">
            <div class="address">
              <i class="icofont-google-map"></i>
              <h4>Location:</h4>
              <p>Chittagong</p>
            </div>

            <div class="email mt-4">
              <i class="icofont-envelope"></i>
              <h4>Email:</h4>
              <p>sacshaurov05@gmail.com</p>
            </div>

            <div class="phone mt-4">
              <i class="icofont-phone"></i>
              <h4>Call:</h4>
              <p>+8801752296069</p>
            </div>

          </div>

        </div>

        <div class="col-lg-5 d-flex align-items-stretch">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7380.796347732003!2d91.77156152493262!3d22.33858949121473!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30acd93857958ddd%3A0xd1ba4cdda8ebde58!2sB-Block%2C%20Chattogram!5e0!3m2!1sen!2sbd!4v1595689110741!5m2!1sen!2sbd" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>

      </div>
    </div>
  </section><!-- End Contact Section -->

</main><!-- End #main -->

{% endblock %}

my_site/templates/projects.html
{% extends "blog/base.html" %}

{% block content %}





  
{% endblock %}

my_site/templates/test.html
{% extends "base.html" %}

{% block content %}
<section id="features" class="features">
  <div class="container jumbotron">
    <h1>You have successfully logged in!</h1>
    <h2>Goto <a href="{% url 'index_page' %}">HomePage</a> to write blogs on your own interest.</h2>
    <p></p>
    <br><br><br><br><br><br><br>
    <br><br><br><br>
  </div>
</section>

{% endblock %}