my_site/categories/urls.py
from django.conf.urls import url
from . import views

app_name = "categories"

urlpatterns = [
    url(r'^$',views.ListCategory.as_view(), name='all'),
    url(r'^new/$', views.CreateCategory.as_view(), name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/', views.SingleCategory.as_view(), name='single'),
    url(r'join/(?P<slug>[-\w]+)/$', views.JoinCategory.as_view(),name='join'),
    url(r'leave/(?P<slug>[-\w]+)/$',views.LeaveCategory.as_view(), name='leave')
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from posts.views import UserPosts

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^$', views.ListCategory2.as_view(), name='index_page'),

    url(r'^categories/', include("categories.urls",namespace="categories")),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^posts/", include("posts.urls", namespace="posts")),

    url(r"^test/$", views.TestPage.as_view(), name='test'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name='thanks'),
    url(r"by/(?P<username>[-\w]+)/$", UserPosts.as_view(),name="for_user"),
    # url(r"^profile/$", views.ProfileView.as_view(), name='profile'),

    path('national_news/', views.national_news, name='national'),
    path('sports/',views.sports_news, name='sports'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

my_site/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.post_detail,name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),

    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),

]

my_site/categories/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='',blank=True)
    members = models.ManyToManyField(User, through="CategoryMember")
    category_pic = models.ImageField(upload_to = 'category_pics', blank=True)

    def __str__(self):
        return self.name

    # WE are saving the model. But before that we are converting
    # the name using slugify and description using misaka.
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    #get_absolute_url is used because it tell the template
    # CreateView to go to the page it is directing.
    # for this example it is directing to go to single page of a category.
    def get_absolute_url(self):
        return reverse("categories:single", kwargs={"slug":self.slug})

    class Meta:
        ordering = ['name']


class CategoryMember(models.Model):
    category = models.ForeignKey(Category, related_name = "memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_categories", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together= ("category", "user")

my_site/categories/forms.py
from django import forms
from . models import Category

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = fields = ("name", "description", "category_pic")

my_site/categories/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import(TemplateView,ListView,
                                DetailView, CreateView,
                                UpdateView, DeleteView,
                                RedirectView,
                                )

from . models import CategoryMember, Category
from . forms import CategoryForm
from sorl.thumbnail import  get_thumbnail
from resizeimage import resizeimage
from accounts.models import UserProfileInfo
from my_site import settings
# Create your views here.

class CreateCategory(CreateView, LoginRequiredMixin):
    fields = ("name", "description", "category_pic")
    widgets = {
            'description':{'class': 'editable medium-editor-textarea postcontent'},
        }
    # template_name = 'categories/category_form.html'
    # After creating Category it will redirect user to that category.
    model = Category


from django import template
register=template.Library()
# nested_to_flat


class SingleCategory(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # self.this_category = get_object_or_404(Category, category.pk==pk)
        category_picture = False

        current_category = Category.objects.filter(
            slug__iexact = self.kwargs.get("slug")
        ).get()

        if current_category.category_pic:
            category_picture = True
            picture = current_category.category_pic
            edited_picture = get_thumbnail(picture, '550x450', quality=99, format='PNG')
        else:
            profile_pic = False
            root = settings.MEDIA_ROOT
            import os
            root1 = os.path.join(root, 'profile_pics/no-image.png')
            picture = root1
            edited_picture = get_thumbnail(picture, '350x350', quality=99, format='PNG')
            # resizeimage.resize_cover(picture, [200, 100], validate=False)
            # rescale_image(picture,width=100,height=100)

        posts = []
        info = []
        continue_reading = False
        for post in current_category.posts.all():
            info.clear()
            info.append(post.user.username)
            info.append(post.pk)
            info.append(post.title)
            info.append(post.created_at)
            info.append(post.category.slug)
            info.append(post.category.name)

            if(len(post.message_html) >300 ):
                continue_reading = True
            else:
                continue_reading = False
            info.append(post.message_html[3:300])
            info.append(continue_reading)

            posts.append(info[:])

        print('\n last info \n',info[:])
        print('\n posts \n',posts[:])

        print(current_category.category_pic)
        category_info = {
            'picture':edited_picture,
            'category_picture':category_picture,
            'posts':posts
        }
        context['category_info'] = category_info
        return context


class ListCategory(ListView):
    model = Category


class JoinCategory(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("categories:single", kwargs={'slug':self.kwargs.get("slug")})

    def get(self,request, *args, **kwargs):
        category = get_object_or_404(Category, slug=self.kwargs.get("slug"))

        try:
            CategoryMember.objects.create(user=self.request.user, category=category)
        except IntegrityError:
            messages.warning(self.request, ("Warning already a member of {}".format(category.name)))
        else:
            messages.success(self.request, "You are now a member of the {} Category.".format(category.name))

        return super().get(request, *args, **kwargs)


class LeaveCategory(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self,*args, **kwargs):
        return reverse("categories:single", kwargs={'slug':self.kwargs.get("slug")})

    def get(self,request, *args, **kwargs):

        try:
            membership = CategoryMember.objects.filter(
                user=self.request.user,
                category__slug = self.kwargs.get("slug")
            )
        except CategoryMember.DoesNotExist:
            messages.warning(self.request, "You can't leave as you didn't join this category.")
        else:
            membership.delete()
            messages.success(self.request, "You have left this group")

        return super().get(request,*args,**kwargs)

my_site/categories/templates/categories/category_base.html
{% extends "base.html" %}
{% block content %}
<section id="steps" class="steps section-bg">
  <div class="container">
      {% block precategory %}

      {% endblock %}

      {% block category_content %}

      {% endblock %}

      {% block postcategory %}

      {% endblock %}
  </div>
</section>


{% endblock %}

my_site/categories/templates/categories/category_detail.html
{% extends "categories/category_base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static "assets/css/style2.css" %}">


{% block precategory %}
<div class="jumbotron">

    <div class="row">
      <div class="col-md-8.5">
        <div class="image">
          {% if category_info.category_picture %}
            <img src="{{category_info.picture.url}}" alt="">
          {% endif %}
        </div>
        <div class="col-md-3.5"> </div> <br>
      </div>
    </div>

  <h2><strong>Name of the Group: {{category.name}}</strong> </h2>
  <h5>Members: {{category.members.count}}</h3>
  <h5>Posts: {{category.posts.count}} </h4>

  <div class="content">
    {% if user in category.members.all %}
      <br>
      <a href="{% url 'categories:leave' slug=category.slug %}"class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon"></span> Leave {{category.name}}</a>
      <a href="{% url 'posts:create' %}" class="btn btn-lg btn-fill btn-primary">Create a Post!</a> </h2>

  	{% else %}
    <br>
      <a href="{% url 'categories:join' slug=category.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon"></span><h5>Join <strong>{{category.name}}</strong> </h4> </a>
      <h6><br><strong>***Join {{category.name}} to write your own blog!</strong> </h4>
    {% endif %}
  </div>
<h3>{{warning}}</h3>
  </div>
{% endblock %}

{% block category_content %}
   {# See, post model in posts/models.py file.. There is a
   group model is connected with ForeignKey with post model.
   and related_name=posts. so we can call category.posts.count.
   we, can also call category.category.count. but here, it seems
   easy and makes sense to use related_name posts.
   that means, category.posts.count #}

    {% if category.posts.count == 0 %}
      <h2>No posts in this category!<br> <a href="{% url 'posts:create' %}">Write a Post</a></h2>

    {% else %}

      {% for post in category_info.posts %}
        {# {% for post in post1 %} #}

                <hr>
                <div class="row">
                  <div class="col-md-2">  </div>

                  <div class="col-md-8">

                      <div class="techfont">
                        <h3 class="category_name"><br><a href="{% url 'posts:single' username=post.0 pk=post.1 %}"><strong>{{post.2}} </strong> </a></h2>
                        <h6><a href="{% url 'posts:for_user' username=post.0 %}">{{post.0}}</a>
                        <time class="time"><a href="{% url 'posts:single' username=post.0 pk=post.1 %}"></a>{{post.3}} </time>

                        <span>in <a href="{% url 'categories:single' slug=post.4 %}">{{post.5}}</a> </span>
                        <br>

                        <br>
                        {% if post.7 %}
                        <h3 class="message">{{post.6|safe}}...<a style="font-size: 18px; color:#22d8b6" href="{% url 'posts:single' username=post.0 pk=post.1 %}">continue reading</a></h3>
                        {% else %}
                        <h3 class="message">{{post.6|safe}}</h3>
                        {% endif %}
                        {# <h3>{{post.7}}</h3> #}

                        {% if user.is_authenticated and user.username == post.0 and not hide_delete%}
                          <a href="{% url 'posts:delete' pk=post.1 %}" title="delete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span>
                          </a>
                        {% endif %}

                      </div>
                  </div>
                </div>
                <hr>
        {# {% endfor %} #}

      {% endfor %}
    {% endif %}
{% endblock %}

my_site/categories/templates/categories/category_form.html
{% extends "categories/category_base.html" %}
{% load bootstrap3 %}

{% block category_content %}
  <div class="container jumbotron">
    <h3>Create a new Category</h3>
    {# #action= create, because it will tell the CreateView
    # to create a category of the provided field. #}
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
  </div>

  <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

my_site/categories/templates/categories/category_list.html
{% extends "categories/category_base.html" %}

{% block precategory %}
<div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
        <h2><strong>Welcome in the Category Page
          <a href="{% url 'posts:for_user' username=user.username %}">{{user.username}}</a>
        </strong> </h2>
      {% endif %}
        <h2>Categories are listed below</h2>
        <h5><strong>Total Categories: {{object_list.count}}</strong> </h6>
        <h5>Choose a category of your own interest and write your own blog.
        You can also see blogs which was written by others also.</h5>
        {% if user.is_authenticated %}
          <a href="{% url 'categories:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon"></span><strong>Create New Category</strong> </a></a>
        {% endif %}
      </div>
    </div>
  {% endblock %}

  {% block category_content %}
  <div class="container">
    <div class="col-md-12">
      <div class="list-category">
        {% for category in object_list %}
          <a class="link" href="{% url 'categories:single' slug=category.slug %}">
            <h3 class="list-group-item-headning">{{category.name}}</h3>
          </a>
            <div class="list-group-item-text container-fluid">
              {{ category.description|safe }}
              <br>
              <div class="row">
                <div class="col-md-3">
                  <h6><span class="badge">Member{{ category.members.count|pluralize }} :{{category.members.count}}</span></h6>
                </div>
                <div class="col-md-4">
                  <h6><span class="badge">Post{{ category.posts.count|pluralize }} :{{category.posts.count}}</span></h6>
                </div>
              </div>
            </div>

        {% endfor %}
      </div>
    </div>
    </div>
{% endblock %}